### ISSUE TITLE
sanity checks on active violation data / deduplicated data

### ISSUE THREAD

**Issue by seeohareeye** [r-b-g-b/clean-water-tool#21]
One sanity check from Rucker: for the Feb 2019 data set, the system Triple R Mutual and analyte Arsenic should be IN compliance, because the most recent VIOL_END_DATE of 3/31/2017 has the ENF_ACTON_TYPE_ISSUED = RETURN TO COMPLIANCE. However, the Triple R Mutual system for Nitrate is OUT of compliance since the most recent VIOL_END_DATE of 12/31/2018 has only one record, and the ENF_ACTION_TYPE_ISSUED with it is not RETURN TO COMPLIANCE. Note that the SWRCB confirmed that sometimes the enforcement action date associated with the most recent Violation Date may have an older "RETURN TO COMPLIANCE". If you find something like that, flag it, but their guidance is that if you have 2 most recent VIOL_END_DATE records and one has RETURN TO COMPLIANCE associated with it, then the system should be back in compliance.

**Comment by seeohareeye** [comment]
Here's one check-- for the Feb 2019 data set, the system Triple R Mutual and analyte Arsenic should be IN compliance, because the most recent VIOL_END_DATE of 3/31/2017 has the ENF_ACTON_TYPE_ISSUED = RETURN TO COMPLIANCE. However, the Triple R Mutual system for Nitrate is OUT of compliance since the most recent VIOL_END_DATE of 12/31/2018 has only one record, and the ENF_ACTION_TYPE_ISSUED with it is not RETURN TO COMPLIANCE. Note that the SWRCB confirmed that sometimes the enforcement action date associated with the most recent Violation Date may have an older "RETURN TO COMPLIANCE". If you find something like that, flag it, but their guidance is that if you have 2 most recent VIOL_END_DATE records and one has RETURN TO COMPLIANCE associated with it, then the system should be back in compliance.

**Comment by ruckeralex** [comment]
Hi!  looks like the current beta tool reporting format might be generating confusion:
https://aaronhans.github.io/community-water-center/system.html?id=CA5400670

For Triple R Mutual water system, since Arsenic and Nitrate are both shown on reporting page, it implies that both are out of compliance.  However, the reality is that as of February, Arsenic is IN compliance and Nitrate is OUT of compliance.  Can we discuss how to fine-tune presentation so that it's immediately clear which analytes are in compliance?

@r-b-g-b  @aaronhans

**Comment by ruckeralex** [comment]
I think the tool's interpretation of the data set is currently correct.  We can reopen this thread if needed.
